name: First Workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Pring greeting
        run: echo "Hello, ${{ github.actor }}"
      - name: Print goodbye
        run: echo "Goodbye, ${{ github.actor }}"
      - name: Print date and time
        run: |
          echo "The time is $(date)"
          echo "The time is $(date -u)"
